# simulation constants
const DEFAULT_MAX_SPEED_VOLUME_FACTOR = 0.01
const DEFAULT_MAX_SPEED = 4.0
const DEFAULT_MIN_MAX_SPEED = 1.0
const DEFAULT_TIME_STEP = 1 / 40.0
const DEFAULT_NEIGHBORHOOD_VELOCITY_SCALE_FACTOR = 1.0
